name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@master
        with:
          file_or_dir: ./**/*.yml
