name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
      - name: Github Action for yamllint
        uses: ibiqlik/action-yamllint@0.0.1
        with:
          file_or_dir: .
